services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_erudio
    ports:
      - 3308:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", "mysql --protocol=TCP --host=127.0.0.1 --user=\"$${MYSQL_USER}\" --password=\"$${MYSQL_PASSWORD}\" --database=\"$${MYSQL_DATABASE}\" --execute=\"SELECT 1\""]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    networks:
      - erudio-network
  rest-spring-boot-erudio:
    image: liedsonmarchioro/rest-spring-boot-erudio:latest
    restart: always
    build: .
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: admin123
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge
